### ISSUE TITLE
Version 1.0.0

### ISSUE THREAD

**Issue by 256dpi** [gomqtt/message#2]
After #1 we're about to release the first version of this package. The following things need to be done in order to roll out the release:

- [x] @256dpi: Full code review.
- [x] @zhenjl: Short code review.

**Comment by 256dpi** [comment]
@zhenjl: Could you please look at the following lines, there is code commented out which should be either remove or commented:

- [ ] header.go:195
- [ ] header.go:198
- [ ] header.go:207
- [ ] header_test.go:170
- [ ] message_test.go:40 (variable is unused)
- [ ] puback.go:61
- [ ] publish.go:229
- [ ] publish.go:233
- [ ] suback.go:94
- [ ] subscribe.go:164
- [ ] subscribe.go:223
- [ ] subscribe.go:227
- [ ] unsubscribe.go:122
- [ ] unsubscribe.go:183
- [ ] unsubscribe.go:187

I'm about to remove all these lines.

**Comment by zhenjl** [comment]
LGTM
