### ISSUE TITLE
Message inheritance

### ISSUE THREAD

**Issue by 256dpi** [gomqtt/message#3]
Simple messages like `PingreqMessage` inherit fields and methods from other messages as like in this case `DisconnectMessage`. This is basically fine, but the error texts in the embedded messages reefer to their type. This could be misleading if there is an error while encoding that message but the error reefers to this message.

Either we remove the reference to the calling function in the error text (that is anyway visible in the backtrace) or we introduce a common type to inherit from.

**Comment by zhenjl** [comment]
The type is set during `New*()`, like `NewDisconnectMessage()`. So any line that refers to the message type should work as expected.

**Comment by 256dpi** [comment]
Even hardcoded messages like: <https://github.com/gomqtt/message/blob/master/puback.go#L73>?

**Comment by zhenjl** [comment]
That's a good catch. We maybe able to change it to something like `fmt.Errorf(this.Name()+"/Encode`...

Wanna try that?

**Comment by zhenjl** [comment]
Awesome. Thx!

Thx

Jian
